package androidx.compose.material3.tokens;

/* JADX INFO: compiled from: r8-map-id-0d0aa97d1fad3edd99b81b175d33e009605b3d4793e5c1d21bed0e5a39522f8f */
/* JADX INFO: loaded from: classes.dex */
public abstract class ColorLightTokens {
    public static final long Background;
    public static final long Error;
    public static final long ErrorContainer;
    public static final long InverseOnSurface;
    public static final long InversePrimary;
    public static final long InverseSurface;
    public static final long OnBackground;
    public static final long OnError;
    public static final long OnErrorContainer;
    public static final long OnPrimary;
    public static final long OnPrimaryContainer;
    public static final long OnPrimaryFixed;
    public static final long OnPrimaryFixedVariant;
    public static final long OnSecondary;
    public static final long OnSecondaryContainer;
    public static final long OnSecondaryFixed;
    public static final long OnSecondaryFixedVariant;
    public static final long OnSurface;
    public static final long OnSurfaceVariant;
    public static final long OnTertiary;
    public static final long OnTertiaryContainer;
    public static final long OnTertiaryFixed;
    public static final long OnTertiaryFixedVariant;
    public static final long Outline;
    public static final long OutlineVariant;
    public static final long Primary;
    public static final long PrimaryContainer;
    public static final long PrimaryFixed;
    public static final long PrimaryFixedDim;
    public static final long Scrim;
    public static final long Secondary;
    public static final long SecondaryContainer;
    public static final long SecondaryFixed;
    public static final long SecondaryFixedDim;
    public static final long Surface;
    public static final long SurfaceBright;
    public static final long SurfaceContainer;
    public static final long SurfaceContainerHigh;
    public static final long SurfaceContainerHighest;
    public static final long SurfaceContainerLow;
    public static final long SurfaceContainerLowest;
    public static final long SurfaceDim;
    public static final long SurfaceVariant;
    public static final long Tertiary;
    public static final long TertiaryContainer;
    public static final long TertiaryFixed;
    public static final long TertiaryFixedDim;

    static {
        long j = PaletteTokens.Neutral98;
        Background = j;
        Error = PaletteTokens.Error40;
        ErrorContainer = PaletteTokens.Error90;
        InverseOnSurface = PaletteTokens.Neutral95;
        long j2 = PaletteTokens.Primary80;
        InversePrimary = j2;
        InverseSurface = PaletteTokens.Neutral20;
        long j3 = PaletteTokens.Neutral10;
        OnBackground = j3;
        OnError = PaletteTokens.Error100;
        OnErrorContainer = PaletteTokens.Error10;
        OnPrimary = PaletteTokens.Primary100;
        long j4 = PaletteTokens.Primary10;
        OnPrimaryContainer = j4;
        OnPrimaryFixed = j4;
        OnPrimaryFixedVariant = PaletteTokens.Primary30;
        OnSecondary = PaletteTokens.Secondary100;
        long j5 = PaletteTokens.Secondary10;
        OnSecondaryContainer = j5;
        OnSecondaryFixed = j5;
        OnSecondaryFixedVariant = PaletteTokens.Secondary30;
        OnSurface = j3;
        OnSurfaceVariant = PaletteTokens.NeutralVariant30;
        OnTertiary = PaletteTokens.Tertiary100;
        long j6 = PaletteTokens.Tertiary10;
        OnTertiaryContainer = j6;
        OnTertiaryFixed = j6;
        OnTertiaryFixedVariant = PaletteTokens.Tertiary30;
        Outline = PaletteTokens.NeutralVariant50;
        OutlineVariant = PaletteTokens.NeutralVariant80;
        Primary = PaletteTokens.Primary40;
        long j7 = PaletteTokens.Primary90;
        PrimaryContainer = j7;
        PrimaryFixed = j7;
        PrimaryFixedDim = j2;
        Scrim = PaletteTokens.Neutral0;
        Secondary = PaletteTokens.Secondary40;
        long j8 = PaletteTokens.Secondary90;
        SecondaryContainer = j8;
        SecondaryFixed = j8;
        SecondaryFixedDim = PaletteTokens.Secondary80;
        Surface = j;
        SurfaceBright = j;
        SurfaceContainer = PaletteTokens.Neutral94;
        SurfaceContainerHigh = PaletteTokens.Neutral92;
        SurfaceContainerHighest = PaletteTokens.Neutral90;
        SurfaceContainerLow = PaletteTokens.Neutral96;
        SurfaceContainerLowest = PaletteTokens.Neutral100;
        SurfaceDim = PaletteTokens.Neutral87;
        SurfaceVariant = PaletteTokens.NeutralVariant90;
        Tertiary = PaletteTokens.Tertiary40;
        long j9 = PaletteTokens.Tertiary90;
        TertiaryContainer = j9;
        TertiaryFixed = j9;
        TertiaryFixedDim = PaletteTokens.Tertiary80;
    }
}
