package androidx.compose.material3.tokens;

import androidx.compose.ui.text.font.FontWeight;
import androidx.compose.ui.text.font.GenericFontFamily;
import androidx.compose.ui.text.font.SystemFontFamily;
import androidx.compose.ui.unit.InlineClassHelperKt;
import androidx.compose.ui.unit.TextUnit;
import androidx.compose.ui.unit.TextUnitKt;
import androidx.compose.ui.unit.TextUnitType;

/* JADX INFO: compiled from: r8-map-id-0d0aa97d1fad3edd99b81b175d33e009605b3d4793e5c1d21bed0e5a39522f8f */
/* JADX INFO: loaded from: classes.dex */
public abstract class TypeScaleTokens {
    public static final GenericFontFamily BodyLargeEmphasizedFont;
    public static final long BodyLargeEmphasizedLineHeight;
    public static final long BodyLargeEmphasizedSize;
    public static final long BodyLargeEmphasizedTracking;
    public static final FontWeight BodyLargeEmphasizedWeight;
    public static final GenericFontFamily BodyLargeFont;
    public static final long BodyLargeLineHeight;
    public static final long BodyLargeSize;
    public static final long BodyLargeTracking;
    public static final FontWeight BodyLargeWeight;
    public static final GenericFontFamily BodyMediumEmphasizedFont;
    public static final long BodyMediumEmphasizedLineHeight;
    public static final long BodyMediumEmphasizedSize;
    public static final long BodyMediumEmphasizedTracking;
    public static final FontWeight BodyMediumEmphasizedWeight;
    public static final GenericFontFamily BodyMediumFont;
    public static final long BodyMediumLineHeight;
    public static final long BodyMediumSize;
    public static final long BodyMediumTracking;
    public static final FontWeight BodyMediumWeight;
    public static final GenericFontFamily BodySmallEmphasizedFont;
    public static final long BodySmallEmphasizedLineHeight;
    public static final long BodySmallEmphasizedSize;
    public static final long BodySmallEmphasizedTracking;
    public static final FontWeight BodySmallEmphasizedWeight;
    public static final GenericFontFamily BodySmallFont;
    public static final long BodySmallLineHeight;
    public static final long BodySmallSize;
    public static final long BodySmallTracking;
    public static final FontWeight BodySmallWeight;
    public static final GenericFontFamily DisplayLargeEmphasizedFont;
    public static final long DisplayLargeEmphasizedLineHeight;
    public static final long DisplayLargeEmphasizedSize;
    public static final long DisplayLargeEmphasizedTracking;
    public static final FontWeight DisplayLargeEmphasizedWeight;
    public static final GenericFontFamily DisplayLargeFont;
    public static final long DisplayLargeLineHeight;
    public static final long DisplayLargeSize;
    public static final long DisplayLargeTracking;
    public static final FontWeight DisplayLargeWeight;
    public static final GenericFontFamily DisplayMediumEmphasizedFont;
    public static final long DisplayMediumEmphasizedLineHeight;
    public static final long DisplayMediumEmphasizedSize;
    public static final long DisplayMediumEmphasizedTracking;
    public static final FontWeight DisplayMediumEmphasizedWeight;
    public static final GenericFontFamily DisplayMediumFont;
    public static final long DisplayMediumLineHeight;
    public static final long DisplayMediumSize;
    public static final long DisplayMediumTracking;
    public static final FontWeight DisplayMediumWeight;
    public static final GenericFontFamily DisplaySmallEmphasizedFont;
    public static final long DisplaySmallEmphasizedLineHeight;
    public static final long DisplaySmallEmphasizedSize;
    public static final long DisplaySmallEmphasizedTracking;
    public static final FontWeight DisplaySmallEmphasizedWeight;
    public static final GenericFontFamily DisplaySmallFont;
    public static final long DisplaySmallLineHeight;
    public static final long DisplaySmallSize;
    public static final long DisplaySmallTracking;
    public static final FontWeight DisplaySmallWeight;
    public static final GenericFontFamily HeadlineLargeEmphasizedFont;
    public static final long HeadlineLargeEmphasizedLineHeight;
    public static final long HeadlineLargeEmphasizedSize;
    public static final long HeadlineLargeEmphasizedTracking;
    public static final FontWeight HeadlineLargeEmphasizedWeight;
    public static final GenericFontFamily HeadlineLargeFont;
    public static final long HeadlineLargeLineHeight;
    public static final long HeadlineLargeSize;
    public static final long HeadlineLargeTracking;
    public static final FontWeight HeadlineLargeWeight;
    public static final GenericFontFamily HeadlineMediumEmphasizedFont;
    public static final long HeadlineMediumEmphasizedLineHeight;
    public static final long HeadlineMediumEmphasizedSize;
    public static final long HeadlineMediumEmphasizedTracking;
    public static final FontWeight HeadlineMediumEmphasizedWeight;
    public static final GenericFontFamily HeadlineMediumFont;
    public static final long HeadlineMediumLineHeight;
    public static final long HeadlineMediumSize;
    public static final long HeadlineMediumTracking;
    public static final FontWeight HeadlineMediumWeight;
    public static final GenericFontFamily HeadlineSmallEmphasizedFont;
    public static final long HeadlineSmallEmphasizedLineHeight;
    public static final long HeadlineSmallEmphasizedSize;
    public static final long HeadlineSmallEmphasizedTracking;
    public static final FontWeight HeadlineSmallEmphasizedWeight;
    public static final GenericFontFamily HeadlineSmallFont;
    public static final long HeadlineSmallLineHeight;
    public static final long HeadlineSmallSize;
    public static final long HeadlineSmallTracking;
    public static final FontWeight HeadlineSmallWeight;
    public static final GenericFontFamily LabelLargeEmphasizedFont;
    public static final long LabelLargeEmphasizedLineHeight;
    public static final long LabelLargeEmphasizedSize;
    public static final long LabelLargeEmphasizedTracking;
    public static final FontWeight LabelLargeEmphasizedWeight;
    public static final GenericFontFamily LabelLargeFont;
    public static final long LabelLargeLineHeight;
    public static final long LabelLargeSize;
    public static final long LabelLargeTracking;
    public static final FontWeight LabelLargeWeight;
    public static final GenericFontFamily LabelMediumEmphasizedFont;
    public static final long LabelMediumEmphasizedLineHeight;
    public static final long LabelMediumEmphasizedSize;
    public static final long LabelMediumEmphasizedTracking;
    public static final FontWeight LabelMediumEmphasizedWeight;
    public static final GenericFontFamily LabelMediumFont;
    public static final long LabelMediumLineHeight;
    public static final long LabelMediumSize;
    public static final long LabelMediumTracking;
    public static final FontWeight LabelMediumWeight;
    public static final GenericFontFamily LabelSmallEmphasizedFont;
    public static final long LabelSmallEmphasizedLineHeight;
    public static final long LabelSmallEmphasizedSize;
    public static final long LabelSmallEmphasizedTracking;
    public static final FontWeight LabelSmallEmphasizedWeight;
    public static final GenericFontFamily LabelSmallFont;
    public static final long LabelSmallLineHeight;
    public static final long LabelSmallSize;
    public static final long LabelSmallTracking;
    public static final FontWeight LabelSmallWeight;
    public static final GenericFontFamily TitleLargeEmphasizedFont;
    public static final long TitleLargeEmphasizedLineHeight;
    public static final long TitleLargeEmphasizedSize;
    public static final long TitleLargeEmphasizedTracking;
    public static final FontWeight TitleLargeEmphasizedWeight;
    public static final GenericFontFamily TitleLargeFont;
    public static final long TitleLargeLineHeight;
    public static final long TitleLargeSize;
    public static final long TitleLargeTracking;
    public static final FontWeight TitleLargeWeight;
    public static final GenericFontFamily TitleMediumEmphasizedFont;
    public static final long TitleMediumEmphasizedLineHeight;
    public static final long TitleMediumEmphasizedSize;
    public static final long TitleMediumEmphasizedTracking;
    public static final FontWeight TitleMediumEmphasizedWeight;
    public static final GenericFontFamily TitleMediumFont;
    public static final long TitleMediumLineHeight;
    public static final long TitleMediumSize;
    public static final long TitleMediumTracking;
    public static final FontWeight TitleMediumWeight;
    public static final GenericFontFamily TitleSmallEmphasizedFont;
    public static final long TitleSmallEmphasizedLineHeight;
    public static final long TitleSmallEmphasizedSize;
    public static final long TitleSmallEmphasizedTracking;
    public static final FontWeight TitleSmallEmphasizedWeight;
    public static final GenericFontFamily TitleSmallFont;
    public static final long TitleSmallLineHeight;
    public static final long TitleSmallSize;
    public static final long TitleSmallTracking;
    public static final FontWeight TitleSmallWeight;

    static {
        FontWeight fontWeight = TypefaceTokens.WeightBold;
        GenericFontFamily genericFontFamily = SystemFontFamily.SansSerif;
        BodyLargeFont = genericFontFamily;
        BodyLargeLineHeight = TextUnitKt.getSp(24.0d);
        BodyLargeSize = TextUnitKt.getSp(16);
        BodyLargeTracking = TextUnitKt.getSp(0.5d);
        FontWeight fontWeight2 = TypefaceTokens.WeightRegular;
        BodyLargeWeight = fontWeight2;
        BodyMediumFont = genericFontFamily;
        BodyMediumLineHeight = TextUnitKt.getSp(20.0d);
        BodyMediumSize = TextUnitKt.getSp(14);
        BodyMediumTracking = TextUnitKt.getSp(0.2d);
        BodyMediumWeight = fontWeight2;
        BodySmallFont = genericFontFamily;
        BodySmallLineHeight = TextUnitKt.getSp(16.0d);
        BodySmallSize = TextUnitKt.getSp(12);
        BodySmallTracking = TextUnitKt.getSp(0.4d);
        BodySmallWeight = fontWeight2;
        DisplayLargeFont = genericFontFamily;
        DisplayLargeLineHeight = TextUnitKt.getSp(64.0d);
        DisplayLargeSize = TextUnitKt.getSp(57);
        long sp = TextUnitKt.getSp(0.2d);
        TextUnitType[] textUnitTypeArr = TextUnit.TextUnitTypes;
        long j = sp & 1095216660480L;
        if (j == 0) {
            InlineClassHelperKt.throwIllegalArgumentException("Cannot perform operation for Unspecified type.");
        }
        DisplayLargeTracking = TextUnitKt.pack(-TextUnit.m727getValueimpl(sp), j);
        DisplayLargeWeight = fontWeight2;
        DisplayMediumFont = genericFontFamily;
        DisplayMediumLineHeight = TextUnitKt.getSp(52.0d);
        DisplayMediumSize = TextUnitKt.getSp(45);
        DisplayMediumTracking = TextUnitKt.getSp(0.0d);
        DisplayMediumWeight = fontWeight2;
        DisplaySmallFont = genericFontFamily;
        DisplaySmallLineHeight = TextUnitKt.getSp(44.0d);
        DisplaySmallSize = TextUnitKt.getSp(36);
        DisplaySmallTracking = TextUnitKt.getSp(0.0d);
        DisplaySmallWeight = fontWeight2;
        HeadlineLargeFont = genericFontFamily;
        HeadlineLargeLineHeight = TextUnitKt.getSp(40.0d);
        HeadlineLargeSize = TextUnitKt.getSp(32);
        HeadlineLargeTracking = TextUnitKt.getSp(0.0d);
        HeadlineLargeWeight = fontWeight2;
        HeadlineMediumFont = genericFontFamily;
        HeadlineMediumLineHeight = TextUnitKt.getSp(36.0d);
        HeadlineMediumSize = TextUnitKt.getSp(28);
        HeadlineMediumTracking = TextUnitKt.getSp(0.0d);
        HeadlineMediumWeight = fontWeight2;
        HeadlineSmallFont = genericFontFamily;
        HeadlineSmallLineHeight = TextUnitKt.getSp(32.0d);
        HeadlineSmallSize = TextUnitKt.getSp(24);
        HeadlineSmallTracking = TextUnitKt.getSp(0.0d);
        HeadlineSmallWeight = fontWeight2;
        LabelLargeFont = genericFontFamily;
        LabelLargeLineHeight = TextUnitKt.getSp(20.0d);
        LabelLargeSize = TextUnitKt.getSp(14);
        LabelLargeTracking = TextUnitKt.getSp(0.1d);
        FontWeight fontWeight3 = TypefaceTokens.WeightMedium;
        LabelLargeWeight = fontWeight3;
        LabelMediumFont = genericFontFamily;
        LabelMediumLineHeight = TextUnitKt.getSp(16.0d);
        LabelMediumSize = TextUnitKt.getSp(12);
        LabelMediumTracking = TextUnitKt.getSp(0.5d);
        LabelMediumWeight = fontWeight3;
        LabelSmallFont = genericFontFamily;
        LabelSmallLineHeight = TextUnitKt.getSp(16.0d);
        LabelSmallSize = TextUnitKt.getSp(11);
        LabelSmallTracking = TextUnitKt.getSp(0.5d);
        LabelSmallWeight = fontWeight3;
        TitleLargeFont = genericFontFamily;
        TitleLargeLineHeight = TextUnitKt.getSp(28.0d);
        TitleLargeSize = TextUnitKt.getSp(22);
        TitleLargeTracking = TextUnitKt.getSp(0.0d);
        TitleLargeWeight = fontWeight2;
        TitleMediumFont = genericFontFamily;
        TitleMediumLineHeight = TextUnitKt.getSp(24.0d);
        TitleMediumSize = TextUnitKt.getSp(16);
        TitleMediumTracking = TextUnitKt.getSp(0.2d);
        TitleMediumWeight = fontWeight3;
        TitleSmallFont = genericFontFamily;
        TitleSmallLineHeight = TextUnitKt.getSp(20.0d);
        TitleSmallSize = TextUnitKt.getSp(14);
        TitleSmallTracking = TextUnitKt.getSp(0.1d);
        TitleSmallWeight = fontWeight3;
        BodyLargeEmphasizedFont = genericFontFamily;
        BodyLargeEmphasizedLineHeight = TextUnitKt.getSp(24.0d);
        BodyLargeEmphasizedSize = TextUnitKt.getSp(16);
        BodyLargeEmphasizedTracking = TextUnitKt.getSp(0.15d);
        BodyLargeEmphasizedWeight = fontWeight3;
        BodyMediumEmphasizedFont = genericFontFamily;
        BodyMediumEmphasizedLineHeight = TextUnitKt.getSp(20.0d);
        BodyMediumEmphasizedSize = TextUnitKt.getSp(14);
        BodyMediumEmphasizedTracking = TextUnitKt.getSp(0.25d);
        BodyMediumEmphasizedWeight = fontWeight3;
        BodySmallEmphasizedFont = genericFontFamily;
        BodySmallEmphasizedLineHeight = TextUnitKt.getSp(16.0d);
        BodySmallEmphasizedSize = TextUnitKt.getSp(12);
        BodySmallEmphasizedTracking = TextUnitKt.getSp(0.4d);
        BodySmallEmphasizedWeight = fontWeight3;
        DisplayLargeEmphasizedFont = genericFontFamily;
        DisplayLargeEmphasizedLineHeight = TextUnitKt.getSp(64.0d);
        DisplayLargeEmphasizedSize = TextUnitKt.getSp(57);
        DisplayLargeEmphasizedTracking = TextUnitKt.getSp(0);
        DisplayLargeEmphasizedWeight = fontWeight3;
        DisplayMediumEmphasizedFont = genericFontFamily;
        DisplayMediumEmphasizedLineHeight = TextUnitKt.getSp(52.0d);
        DisplayMediumEmphasizedSize = TextUnitKt.getSp(45);
        DisplayMediumEmphasizedTracking = TextUnitKt.getSp(0);
        DisplayMediumEmphasizedWeight = fontWeight3;
        DisplaySmallEmphasizedFont = genericFontFamily;
        DisplaySmallEmphasizedLineHeight = TextUnitKt.getSp(44.0d);
        DisplaySmallEmphasizedSize = TextUnitKt.getSp(36);
        DisplaySmallEmphasizedTracking = TextUnitKt.getSp(0);
        DisplaySmallEmphasizedWeight = fontWeight3;
        HeadlineLargeEmphasizedFont = genericFontFamily;
        HeadlineLargeEmphasizedLineHeight = TextUnitKt.getSp(40.0d);
        HeadlineLargeEmphasizedSize = TextUnitKt.getSp(32);
        HeadlineLargeEmphasizedTracking = TextUnitKt.getSp(0);
        HeadlineLargeEmphasizedWeight = fontWeight3;
        HeadlineMediumEmphasizedFont = genericFontFamily;
        HeadlineMediumEmphasizedLineHeight = TextUnitKt.getSp(36.0d);
        HeadlineMediumEmphasizedSize = TextUnitKt.getSp(28);
        HeadlineMediumEmphasizedTracking = TextUnitKt.getSp(0);
        HeadlineMediumEmphasizedWeight = fontWeight3;
        HeadlineSmallEmphasizedFont = genericFontFamily;
        HeadlineSmallEmphasizedLineHeight = TextUnitKt.getSp(32.0d);
        HeadlineSmallEmphasizedSize = TextUnitKt.getSp(24);
        HeadlineSmallEmphasizedTracking = TextUnitKt.getSp(0);
        HeadlineSmallEmphasizedWeight = fontWeight3;
        LabelLargeEmphasizedFont = genericFontFamily;
        LabelLargeEmphasizedLineHeight = TextUnitKt.getSp(20.0d);
        LabelLargeEmphasizedSize = TextUnitKt.getSp(14);
        LabelLargeEmphasizedTracking = TextUnitKt.getSp(0.1d);
        FontWeight fontWeight4 = TypefaceTokens.WeightBold;
        LabelLargeEmphasizedWeight = fontWeight4;
        LabelMediumEmphasizedFont = genericFontFamily;
        LabelMediumEmphasizedLineHeight = TextUnitKt.getSp(16.0d);
        LabelMediumEmphasizedSize = TextUnitKt.getSp(12);
        LabelMediumEmphasizedTracking = TextUnitKt.getSp(0.5d);
        LabelMediumEmphasizedWeight = fontWeight4;
        LabelSmallEmphasizedFont = genericFontFamily;
        LabelSmallEmphasizedLineHeight = TextUnitKt.getSp(16.0d);
        LabelSmallEmphasizedSize = TextUnitKt.getSp(11);
        LabelSmallEmphasizedTracking = TextUnitKt.getSp(0.5d);
        LabelSmallEmphasizedWeight = fontWeight4;
        TitleLargeEmphasizedFont = genericFontFamily;
        TitleLargeEmphasizedLineHeight = TextUnitKt.getSp(28.0d);
        TitleLargeEmphasizedSize = TextUnitKt.getSp(22);
        TitleLargeEmphasizedTracking = TextUnitKt.getSp(0);
        TitleLargeEmphasizedWeight = fontWeight3;
        TitleMediumEmphasizedFont = genericFontFamily;
        TitleMediumEmphasizedLineHeight = TextUnitKt.getSp(24.0d);
        TitleMediumEmphasizedSize = TextUnitKt.getSp(16);
        TitleMediumEmphasizedTracking = TextUnitKt.getSp(0.15d);
        TitleMediumEmphasizedWeight = fontWeight4;
        TitleSmallEmphasizedFont = genericFontFamily;
        TitleSmallEmphasizedLineHeight = TextUnitKt.getSp(20.0d);
        TitleSmallEmphasizedSize = TextUnitKt.getSp(14);
        TitleSmallEmphasizedTracking = TextUnitKt.getSp(0.1d);
        TitleSmallEmphasizedWeight = fontWeight4;
    }
}
