package com.google.android.gms.internal.mlkit_vision_common;

import androidx.compose.ui.unit.Density;
import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;

/* JADX INFO: compiled from: r8-map-id-0d0aa97d1fad3edd99b81b175d33e009605b3d4793e5c1d21bed0e5a39522f8f */
/* JADX INFO: loaded from: classes.dex */
public final class zzeo implements ObjectEncoder {
    public static final zzeo zza = new zzeo();
    public static final FieldDescriptor zzb = new FieldDescriptor("systemInfo", Density.CC.m(Density.CC.m(zzai.class, new zzad(1))));
    public static final FieldDescriptor zzc = new FieldDescriptor("eventName", Density.CC.m(Density.CC.m(zzai.class, new zzad(2))));
    public static final FieldDescriptor zzd = new FieldDescriptor("isThickClient", Density.CC.m(Density.CC.m(zzai.class, new zzad(37))));
    public static final FieldDescriptor zze = new FieldDescriptor("clientType", Density.CC.m(Density.CC.m(zzai.class, new zzad(61))));
    public static final FieldDescriptor zzf = new FieldDescriptor("modelDownloadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(3))));
    public static final FieldDescriptor zzg = new FieldDescriptor("customModelLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(20))));
    public static final FieldDescriptor zzh = new FieldDescriptor("customModelInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(4))));
    public static final FieldDescriptor zzi = new FieldDescriptor("customModelCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(29))));
    public static final FieldDescriptor zzj = new FieldDescriptor("onDeviceFaceDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(5))));
    public static final FieldDescriptor zzk = new FieldDescriptor("onDeviceFaceLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(59))));
    public static final FieldDescriptor zzl = new FieldDescriptor("onDeviceTextDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(6))));
    public static final FieldDescriptor zzm = new FieldDescriptor("onDeviceTextDetectionLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(79))));
    public static final FieldDescriptor zzn = new FieldDescriptor("onDeviceBarcodeDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(7))));
    public static final FieldDescriptor zzo = new FieldDescriptor("onDeviceBarcodeLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(58))));
    public static final FieldDescriptor zzp = new FieldDescriptor("onDeviceImageLabelCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(48))));
    public static final FieldDescriptor zzq = new FieldDescriptor("onDeviceImageLabelLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(49))));
    public static final FieldDescriptor zzr = new FieldDescriptor("onDeviceImageLabelDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(18))));
    public static final FieldDescriptor zzs = new FieldDescriptor("onDeviceObjectCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(26))));
    public static final FieldDescriptor zzt = new FieldDescriptor("onDeviceObjectLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(27))));
    public static final FieldDescriptor zzu = new FieldDescriptor("onDeviceObjectInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(28))));
    public static final FieldDescriptor zzv = new FieldDescriptor("onDevicePoseDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(44))));
    public static final FieldDescriptor zzw = new FieldDescriptor("onDeviceSegmentationLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(45))));
    public static final FieldDescriptor zzx = new FieldDescriptor("onDeviceSmartReplyLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(19))));
    public static final FieldDescriptor zzy = new FieldDescriptor("onDeviceLanguageIdentificationLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(21))));
    public static final FieldDescriptor zzz = new FieldDescriptor("onDeviceTranslationLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(22))));
    public static final FieldDescriptor zzA = new FieldDescriptor("cloudFaceDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(8))));
    public static final FieldDescriptor zzB = new FieldDescriptor("cloudCropHintDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(9))));
    public static final FieldDescriptor zzC = new FieldDescriptor("cloudDocumentTextDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(10))));
    public static final FieldDescriptor zzD = new FieldDescriptor("cloudImagePropertiesDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(11))));
    public static final FieldDescriptor zzE = new FieldDescriptor("cloudImageLabelDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(12))));
    public static final FieldDescriptor zzF = new FieldDescriptor("cloudLandmarkDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(13))));
    public static final FieldDescriptor zzG = new FieldDescriptor("cloudLogoDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(14))));
    public static final FieldDescriptor zzH = new FieldDescriptor("cloudSafeSearchDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(15))));
    public static final FieldDescriptor zzI = new FieldDescriptor("cloudTextDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(16))));
    public static final FieldDescriptor zzJ = new FieldDescriptor("cloudWebSearchDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(17))));
    public static final FieldDescriptor zzK = new FieldDescriptor("automlImageLabelingCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(23))));
    public static final FieldDescriptor zzL = new FieldDescriptor("automlImageLabelingLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(24))));
    public static final FieldDescriptor zzM = new FieldDescriptor("automlImageLabelingInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(25))));
    public static final FieldDescriptor zzN = new FieldDescriptor("isModelDownloadedLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(39))));
    public static final FieldDescriptor zzO = new FieldDescriptor("deleteModelLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(40))));
    public static final FieldDescriptor zzP = new FieldDescriptor("aggregatedAutomlImageLabelingInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(30))));
    public static final FieldDescriptor zzQ = new FieldDescriptor("aggregatedCustomModelInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(31))));
    public static final FieldDescriptor zzR = new FieldDescriptor("aggregatedOnDeviceFaceDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(32))));
    public static final FieldDescriptor zzS = new FieldDescriptor("aggregatedOnDeviceBarcodeDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(33))));
    public static final FieldDescriptor zzT = new FieldDescriptor("aggregatedOnDeviceImageLabelDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(34))));
    public static final FieldDescriptor zzU = new FieldDescriptor("aggregatedOnDeviceObjectInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(35))));
    public static final FieldDescriptor zzV = new FieldDescriptor("aggregatedOnDeviceTextDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(36))));
    public static final FieldDescriptor zzW = new FieldDescriptor("aggregatedOnDevicePoseDetectionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(46))));
    public static final FieldDescriptor zzX = new FieldDescriptor("aggregatedOnDeviceSegmentationLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(47))));
    public static final FieldDescriptor zzY = new FieldDescriptor("pipelineAccelerationInferenceEvents", Density.CC.m(Density.CC.m(zzai.class, new zzad(69))));
    public static final FieldDescriptor zzZ = new FieldDescriptor("remoteConfigLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(42))));
    public static final FieldDescriptor zzaa = new FieldDescriptor("inputImageConstructionLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(50))));
    public static final FieldDescriptor zzab = new FieldDescriptor("leakedHandleEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(51))));
    public static final FieldDescriptor zzac = new FieldDescriptor("cameraSourceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(52))));
    public static final FieldDescriptor zzad = new FieldDescriptor("imageLabelOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(53))));
    public static final FieldDescriptor zzae = new FieldDescriptor("languageIdentificationOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(54))));
    public static final FieldDescriptor zzaf = new FieldDescriptor("faceDetectionOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(60))));
    public static final FieldDescriptor zzag = new FieldDescriptor("documentDetectionOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(85))));
    public static final FieldDescriptor zzah = new FieldDescriptor("documentCroppingOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(86))));
    public static final FieldDescriptor zzai = new FieldDescriptor("documentEnhancementOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(87))));
    public static final FieldDescriptor zzaj = new FieldDescriptor("nlClassifierOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(55))));
    public static final FieldDescriptor zzak = new FieldDescriptor("nlClassifierClientLibraryLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(56))));
    public static final FieldDescriptor zzal = new FieldDescriptor("accelerationAllowlistLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(57))));
    public static final FieldDescriptor zzam = new FieldDescriptor("toxicityDetectionCreateEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(62))));
    public static final FieldDescriptor zzan = new FieldDescriptor("toxicityDetectionLoadEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(63))));
    public static final FieldDescriptor zzao = new FieldDescriptor("toxicityDetectionInferenceEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(64))));
    public static final FieldDescriptor zzap = new FieldDescriptor("barcodeDetectionOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(65))));
    public static final FieldDescriptor zzaq = new FieldDescriptor("customImageLabelOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(66))));
    public static final FieldDescriptor zzar = new FieldDescriptor("codeScannerScanApiEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(67))));
    public static final FieldDescriptor zzas = new FieldDescriptor("codeScannerOptionalModuleEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(68))));
    public static final FieldDescriptor zzat = new FieldDescriptor("onDeviceExplicitContentCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(70))));
    public static final FieldDescriptor zzau = new FieldDescriptor("onDeviceExplicitContentLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(71))));
    public static final FieldDescriptor zzav = new FieldDescriptor("onDeviceExplicitContentInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(72))));
    public static final FieldDescriptor zzaw = new FieldDescriptor("aggregatedOnDeviceExplicitContentLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(73))));
    public static final FieldDescriptor zzax = new FieldDescriptor("onDeviceFaceMeshCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(74))));
    public static final FieldDescriptor zzay = new FieldDescriptor("onDeviceFaceMeshLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(75))));
    public static final FieldDescriptor zzaz = new FieldDescriptor("onDeviceFaceMeshLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(76))));
    public static final FieldDescriptor zzaA = new FieldDescriptor("aggregatedOnDeviceFaceMeshLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(77))));
    public static final FieldDescriptor zzaB = new FieldDescriptor("smartReplyOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(78))));
    public static final FieldDescriptor zzaC = new FieldDescriptor("textDetectionOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(80))));
    public static final FieldDescriptor zzaD = new FieldDescriptor("onDeviceImageQualityAnalysisCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(81))));
    public static final FieldDescriptor zzaE = new FieldDescriptor("onDeviceImageQualityAnalysisLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(82))));
    public static final FieldDescriptor zzaF = new FieldDescriptor("onDeviceImageQualityAnalysisLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(83))));
    public static final FieldDescriptor zzaG = new FieldDescriptor("aggregatedOnDeviceImageQualityAnalysisLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(84))));
    public static final FieldDescriptor zzaH = new FieldDescriptor("imageQualityAnalysisOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(88))));
    public static final FieldDescriptor zzaI = new FieldDescriptor("imageCaptioningOptionalModuleLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(89))));
    public static final FieldDescriptor zzaJ = new FieldDescriptor("onDeviceImageCaptioningCreateLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(90))));
    public static final FieldDescriptor zzaK = new FieldDescriptor("onDeviceImageCaptioningLoadLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(91))));
    public static final FieldDescriptor zzaL = new FieldDescriptor("onDeviceImageCaptioningInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(92))));
    public static final FieldDescriptor zzaM = new FieldDescriptor("aggregatedOnDeviceImageCaptioningInferenceLogEvent", Density.CC.m(Density.CC.m(zzai.class, new zzad(93))));

    @Override // com.google.firebase.encoders.Encoder
    public final void encode(Object obj, Object obj2) {
        zziy zziyVar = (zziy) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(zzb, zziyVar.zza);
        objectEncoderContext.add(zzc, zziyVar.zzb);
        objectEncoderContext.add(zzd, (Object) null);
        objectEncoderContext.add(zze, (Object) null);
        objectEncoderContext.add(zzf, (Object) null);
        objectEncoderContext.add(zzg, (Object) null);
        objectEncoderContext.add(zzh, (Object) null);
        objectEncoderContext.add(zzi, (Object) null);
        objectEncoderContext.add(zzj, (Object) null);
        objectEncoderContext.add(zzk, (Object) null);
        objectEncoderContext.add(zzl, (Object) null);
        objectEncoderContext.add(zzm, (Object) null);
        objectEncoderContext.add(zzn, (Object) null);
        objectEncoderContext.add(zzo, (Object) null);
        objectEncoderContext.add(zzp, (Object) null);
        objectEncoderContext.add(zzq, (Object) null);
        objectEncoderContext.add(zzr, (Object) null);
        objectEncoderContext.add(zzs, (Object) null);
        objectEncoderContext.add(zzt, (Object) null);
        objectEncoderContext.add(zzu, (Object) null);
        objectEncoderContext.add(zzv, (Object) null);
        objectEncoderContext.add(zzw, (Object) null);
        objectEncoderContext.add(zzx, (Object) null);
        objectEncoderContext.add(zzy, (Object) null);
        objectEncoderContext.add(zzz, (Object) null);
        objectEncoderContext.add(zzA, (Object) null);
        objectEncoderContext.add(zzB, (Object) null);
        objectEncoderContext.add(zzC, (Object) null);
        objectEncoderContext.add(zzD, (Object) null);
        objectEncoderContext.add(zzE, (Object) null);
        objectEncoderContext.add(zzF, (Object) null);
        objectEncoderContext.add(zzG, (Object) null);
        objectEncoderContext.add(zzH, (Object) null);
        objectEncoderContext.add(zzI, (Object) null);
        objectEncoderContext.add(zzJ, (Object) null);
        objectEncoderContext.add(zzK, (Object) null);
        objectEncoderContext.add(zzL, (Object) null);
        objectEncoderContext.add(zzM, (Object) null);
        objectEncoderContext.add(zzN, (Object) null);
        objectEncoderContext.add(zzO, (Object) null);
        objectEncoderContext.add(zzP, (Object) null);
        objectEncoderContext.add(zzQ, (Object) null);
        objectEncoderContext.add(zzR, (Object) null);
        objectEncoderContext.add(zzS, (Object) null);
        objectEncoderContext.add(zzT, (Object) null);
        objectEncoderContext.add(zzU, (Object) null);
        objectEncoderContext.add(zzV, (Object) null);
        objectEncoderContext.add(zzW, (Object) null);
        objectEncoderContext.add(zzX, (Object) null);
        objectEncoderContext.add(zzY, (Object) null);
        objectEncoderContext.add(zzZ, (Object) null);
        objectEncoderContext.add(zzaa, zziyVar.zzc);
        objectEncoderContext.add(zzab, (Object) null);
        objectEncoderContext.add(zzac, (Object) null);
        objectEncoderContext.add(zzad, (Object) null);
        objectEncoderContext.add(zzae, (Object) null);
        objectEncoderContext.add(zzaf, (Object) null);
        objectEncoderContext.add(zzag, (Object) null);
        objectEncoderContext.add(zzah, (Object) null);
        objectEncoderContext.add(zzai, (Object) null);
        objectEncoderContext.add(zzaj, (Object) null);
        objectEncoderContext.add(zzak, (Object) null);
        objectEncoderContext.add(zzal, (Object) null);
        objectEncoderContext.add(zzam, (Object) null);
        objectEncoderContext.add(zzan, (Object) null);
        objectEncoderContext.add(zzao, (Object) null);
        objectEncoderContext.add(zzap, (Object) null);
        objectEncoderContext.add(zzaq, (Object) null);
        objectEncoderContext.add(zzar, (Object) null);
        objectEncoderContext.add(zzas, (Object) null);
        objectEncoderContext.add(zzat, (Object) null);
        objectEncoderContext.add(zzau, (Object) null);
        objectEncoderContext.add(zzav, (Object) null);
        objectEncoderContext.add(zzaw, (Object) null);
        objectEncoderContext.add(zzax, (Object) null);
        objectEncoderContext.add(zzay, (Object) null);
        objectEncoderContext.add(zzaz, (Object) null);
        objectEncoderContext.add(zzaA, (Object) null);
        objectEncoderContext.add(zzaB, (Object) null);
        objectEncoderContext.add(zzaC, (Object) null);
        objectEncoderContext.add(zzaD, (Object) null);
        objectEncoderContext.add(zzaE, (Object) null);
        objectEncoderContext.add(zzaF, (Object) null);
        objectEncoderContext.add(zzaG, (Object) null);
        objectEncoderContext.add(zzaH, (Object) null);
        objectEncoderContext.add(zzaI, (Object) null);
        objectEncoderContext.add(zzaJ, (Object) null);
        objectEncoderContext.add(zzaK, (Object) null);
        objectEncoderContext.add(zzaL, (Object) null);
        objectEncoderContext.add(zzaM, (Object) null);
    }
}
