package com.google.android.gms.internal.mlkit_vision_common;

import androidx.emoji2.text.MetadataListReader;
import androidx.exifinterface.media.ExifInterfaceUtils;
import androidx.fragment.app.FragmentAnim;
import androidx.lifecycle.compose.FlowExtKt;
import androidx.lifecycle.compose.LifecycleEffectKt;
import androidx.lifecycle.viewmodel.compose.ViewModelKt;
import androidx.navigation.NavArgumentKt;
import androidx.navigation.NavControllerViewModel;
import androidx.navigation.NavDestination;
import androidx.navigation.NavGraph;
import androidx.navigation.NavOptionsBuilderKt;
import androidx.navigation.NavigatorProvider;
import androidx.navigation.compose.DialogHostKt;
import androidx.navigation.compose.NavBackStackEntryProviderKt;
import androidx.navigation.compose.NavGraphBuilderKt;
import androidx.navigation.compose.NavHostControllerKt;
import androidx.navigation.compose.NavHostKt;
import androidx.navigationevent.NavigationEventInfo;
import androidx.navigationevent.NavigationEventTransitionState;
import androidx.navigationevent.NavigationEvent_androidKt;
import androidx.recyclerview.widget.ScrollbarHelper;
import androidx.room.util.CursorUtil;
import androidx.savedstate.SavedStateReader;
import androidx.savedstate.ViewTreeSavedStateRegistryOwner;
import androidx.tracing.Trace;
import androidx.transition.Transition;
import androidx.transition.ViewGroupUtils;
import androidx.transition.ViewUtilsApi19;
import androidx.viewbinding.ViewBindings;
import coil.ImageLoaders;
import coil.decode.DecodeUtils;
import coil.decode.ImageSource$Metadata;
import coil.network.CacheStrategy;
import coil.size.Dimension;
import coil.util.Bitmaps;
import coil.util.Collections;
import coil.util.DrawableUtils;
import coil.util.FileSystems;
import coil.util.Lifecycles;
import com.github.kr328.clash.ApkDownloader;
import com.github.kr328.clash.MainApplication;
import com.github.kr328.clash.common.compat.ContextKt;
import com.github.kr328.clash.common.compat.IntentsKt;
import com.github.kr328.clash.common.compat.ServicesKt;
import com.github.kr328.clash.common.compat.TvKt;
import com.github.kr328.clash.common.util.ComponentsKt;
import com.github.kr328.clash.common.util.IntentKt;
import com.github.kr328.clash.common.util.ParcelableKt;
import com.github.kr328.clash.compose.ApkBrokenScreenKt;
import com.github.kr328.clash.compose.AppCrashedScreenKt;
import com.github.kr328.clash.compose.FilesScreenKt;
import com.github.kr328.clash.compose.HwidLimitDialogKt;
import com.github.kr328.clash.compose.LogcatScreenKt;
import com.github.kr328.clash.compose.LogsScreenKt;
import com.github.kr328.clash.compose.MainAppKt;
import com.github.kr328.clash.compose.PropertiesScreenKt;
import com.github.kr328.clash.compose.ProvidersScreenKt;
import com.github.kr328.clash.compose.UpdateDialogKt;
import com.github.kr328.clash.compose.home.HomeScreenKt;
import com.github.kr328.clash.compose.profiles.ProfileCardKt;
import com.github.kr328.clash.compose.proxy.ProxyScreenKt;
import com.github.kr328.clash.compose.qrcode.TvQrCodeSheetKt;
import com.github.kr328.clash.compose.util.FormatKt;
import com.github.kr328.clash.compose.util.TvGlassTabRowKt;
import com.github.kr328.clash.core.util.TrafficKt;
import com.github.kr328.clash.design.model.LogFile;
import com.github.kr328.clash.design.util.I18nKt;
import com.github.kr328.clash.service.ProfileProcessorKt;
import com.github.kr328.clash.service.StatusProvider;
import com.github.kr328.clash.service.data.DaosKt;
import com.github.kr328.clash.service.document.Paths;
import com.github.kr328.clash.service.util.BroadcastKt;
import com.github.kr328.clash.service.util.CoroutineKt;
import com.github.kr328.clash.service.util.DatabaseKt;
import com.github.kr328.clash.service.util.DeviceInfoKt;
import com.github.kr328.clash.service.util.FilesKt;
import com.github.kr328.clash.service.util.NetKt;
import com.github.kr328.clash.util.ClashKt;
import com.github.kr328.clash.util.ContentKt;
import com.github.kr328.clash.util.LocalNetworkKt;
import com.github.kr328.clash.util.QrCodeGeneratorKt;
import com.github.kr328.clash.util.RemoteKt;
import com.github.kr328.kaidl.SuspendTransactionKt;
import com.google.android.datatransport.Transformer;
import com.google.android.datatransport.cct.StringMerger;
import com.google.android.gms.common.api.internal.TaskUtil;
import com.google.android.gms.common.util.DeviceProperties;
import com.google.android.gms.internal.mlkit_common.zzt;
import com.google.android.gms.signin.zaa;
import com.google.android.gms.tasks.Tasks;
import com.google.android.material.color.MaterialColors;
import com.google.android.material.resources.MaterialResources;
import com.google.android.material.resources.TypefaceUtils;
import com.google.android.material.shape.CornerTreatment;
import com.google.android.material.shape.MaterialShapeUtils;
import com.google.android.material.textfield.IconHelper;
import com.google.firebase.encoders.config.EncoderConfig;

/* JADX INFO: compiled from: r8-map-id-0d0aa97d1fad3edd99b81b175d33e009605b3d4793e5c1d21bed0e5a39522f8f */
/* JADX INFO: loaded from: classes.dex */
public final class zzmw implements Transformer {
    public static zzmw zza;
    public static final zzmw zza$1 = new zzmw(1);
    public static final /* synthetic */ zzmw zza$2 = new zzmw(2);
    public static final /* synthetic */ zzmw zza$3 = new zzmw(3);
    public final /* synthetic */ int $r8$classId;

    public /* synthetic */ zzmw(int i) {
        this.$r8$classId = i;
    }

    public static synchronized void zza() {
        if (zza == null) {
            zza = new zzmw(0);
        }
    }

    @Override // com.google.android.datatransport.Transformer
    public Object apply(Object obj) {
        switch (this.$r8$classId) {
            case 2:
                break;
        }
        return (byte[]) obj;
    }

    public void configure(EncoderConfig encoderConfig) {
        encoderConfig.registerEncoder(zziy.class, zzeo.zza);
        encoderConfig.registerEncoder(zzla.class, zzgu.zza);
        encoderConfig.registerEncoder(zziz.class, zzep.zza);
        encoderConfig.registerEncoder(zzjc.class, zzer.zza);
        encoderConfig.registerEncoder(TvQrCodeSheetKt.class, zzeq.zza);
        encoderConfig.registerEncoder(zzjb.class, zzes.zza);
        encoderConfig.registerEncoder(ComponentsKt.class, zzdr.zza);
        encoderConfig.registerEncoder(TvKt.class, zzdq.zza);
        encoderConfig.registerEncoder(HomeScreenKt.class, zzeh.zza);
        encoderConfig.registerEncoder(com.google.android.gms.internal.mlkit_common.zzy.class, zzgm.zza);
        encoderConfig.registerEncoder(ServicesKt.class, zzdp.zza);
        encoderConfig.registerEncoder(IntentsKt.class, zzdo.zza);
        encoderConfig.registerEncoder(zzjl.class, zzfd.zza);
        encoderConfig.registerEncoder(zzlu.class, zzeb.zza);
        encoderConfig.registerEncoder(PropertiesScreenKt.class, zzee.zza);
        encoderConfig.registerEncoder(LogsScreenKt.class, zzea.zza);
        encoderConfig.registerEncoder(zzjm.class, zzfe.zza);
        encoderConfig.registerEncoder(com.google.android.gms.internal.mlkit_common.zzak.class, zzgj.zza);
        encoderConfig.registerEncoder(zzt.class, zzgk.zza);
        encoderConfig.registerEncoder(DeviceProperties.class, zzgi.zza);
        encoderConfig.registerEncoder(FormatKt.class, zzey.zza);
        encoderConfig.registerEncoder(IconHelper.class, zzcy.zza);
        encoderConfig.registerEncoder(TvGlassTabRowKt.class, zzez.zza);
        encoderConfig.registerEncoder(StatusProvider.Companion.class, zzfm.zza);
        encoderConfig.registerEncoder(Paths.class, zzfp.zza);
        encoderConfig.registerEncoder(DaosKt.class, zzfo.zza);
        encoderConfig.registerEncoder(zzjv.class, zzfn.zza);
        encoderConfig.registerEncoder(LocalNetworkKt.class, zzfy.zza);
        encoderConfig.registerEncoder(QrCodeGeneratorKt.class, zzfz.zza);
        encoderConfig.registerEncoder(SuspendTransactionKt.class, zzgb.zza);
        encoderConfig.registerEncoder(RemoteKt.class, zzga.zza);
        encoderConfig.registerEncoder(zzjf.class, zzex.zza);
        encoderConfig.registerEncoder(StringMerger.class, zzgc.zza);
        encoderConfig.registerEncoder(zzkl.class, zzgd.zza);
        encoderConfig.registerEncoder(zaa.class, zzge.zza);
        encoderConfig.registerEncoder(TaskUtil.class, zzgf.zza);
        encoderConfig.registerEncoder(zzkp.class, zzgg.zza);
        encoderConfig.registerEncoder(zzko.class, zzgh.zza);
        encoderConfig.registerEncoder(ContentKt.class, zzfu.zza);
        encoderConfig.registerEncoder(zzit.class, zzem.zza);
        encoderConfig.registerEncoder(NetKt.class, zzfw.zza);
        encoderConfig.registerEncoder(FilesKt.class, zzfv.zza);
        encoderConfig.registerEncoder(ClashKt.class, zzfx.zza);
        encoderConfig.registerEncoder(com.google.android.gms.internal.mlkit_common.zzu.class, zzgl.zza);
        encoderConfig.registerEncoder(zzlg.class, zzha.zza);
        encoderConfig.registerEncoder(ImageSource$Metadata.class, zzdd.zza);
        encoderConfig.registerEncoder(ImageLoaders.class, zzdb.zza);
        encoderConfig.registerEncoder(ViewBindings.class, zzda.zza);
        encoderConfig.registerEncoder(DecodeUtils.class, zzdc.zza);
        encoderConfig.registerEncoder(Dimension.class, zzdf.zza);
        encoderConfig.registerEncoder(CacheStrategy.Companion.class, zzde.zza);
        encoderConfig.registerEncoder(Bitmaps.class, zzdg.zza);
        encoderConfig.registerEncoder(Collections.class, zzdh.zza);
        encoderConfig.registerEncoder(FileSystems.class, zzdi.zza);
        encoderConfig.registerEncoder(Lifecycles.class, zzdj.zza);
        encoderConfig.registerEncoder(DrawableUtils.class, zzdk.zza);
        encoderConfig.registerEncoder(ViewTreeSavedStateRegistryOwner.class, zzcu.zza);
        encoderConfig.registerEncoder(Transition.EpicenterCallback.class, zzcw.zza);
        encoderConfig.registerEncoder(Trace.class, zzcv.zza);
        encoderConfig.registerEncoder(zzir.class, zzek.zza);
        encoderConfig.registerEncoder(IntentKt.class, zzds.zza);
        encoderConfig.registerEncoder(MetadataListReader.class, zzbu.zza);
        encoderConfig.registerEncoder(zzaq.class, zzbv.zza);
        encoderConfig.registerEncoder(HwidLimitDialogKt.class, zzdy.zza);
        encoderConfig.registerEncoder(ExifInterfaceUtils.class, zzbw.zza);
        encoderConfig.registerEncoder(zzas.class, zzbx.zza);
        encoderConfig.registerEncoder(NavArgumentKt.class, zzcc.zza);
        encoderConfig.registerEncoder(zzay.class, zzcd.zza);
        encoderConfig.registerEncoder(FlowExtKt.class, zzby.zza);
        encoderConfig.registerEncoder(FragmentAnim.class, zzbz.zza);
        encoderConfig.registerEncoder(DialogHostKt.class, zzci.zza);
        encoderConfig.registerEncoder(NavigatorProvider.Companion.class, zzcj.zza);
        encoderConfig.registerEncoder(NavHostKt.class, zzcm.zza);
        encoderConfig.registerEncoder(NavHostControllerKt.class, zzcn.zza);
        encoderConfig.registerEncoder(SavedStateReader.class, zzcs.zza);
        encoderConfig.registerEncoder(CursorUtil.class, zzct.zza);
        encoderConfig.registerEncoder(NavigationEventTransitionState.class, zzco.zza);
        encoderConfig.registerEncoder(NavigationEventInfo.class, zzcp.zza);
        encoderConfig.registerEncoder(ScrollbarHelper.class, zzcq.zza);
        encoderConfig.registerEncoder(NavigationEvent_androidKt.class, zzcr.zza);
        encoderConfig.registerEncoder(MaterialResources.class, zzgp.zza);
        encoderConfig.registerEncoder(zzlh.class, zzdt.zza);
        encoderConfig.registerEncoder(Tasks.class, zzew.zza);
        encoderConfig.registerEncoder(zzg.class, zzev.zza);
        encoderConfig.registerEncoder(zzli.class, zzec.zza);
        encoderConfig.registerEncoder(zzln.class, zzgo.zza);
        encoderConfig.registerEncoder(MaterialColors.class, zzgn.zza);
        encoderConfig.registerEncoder(zzlp.class, zzgq.zza);
        encoderConfig.registerEncoder(zzf.class, zzei.zza);
        encoderConfig.registerEncoder(MaterialShapeUtils.class, zzhc.zza);
        encoderConfig.registerEncoder(CornerTreatment.class, zzhd.zza);
        encoderConfig.registerEncoder(TypefaceUtils.class, zzhb.zza);
        encoderConfig.registerEncoder(zzkv.class, zzgr.zza);
        encoderConfig.registerEncoder(zziq.class, zzej.zza);
        encoderConfig.registerEncoder(ProxyScreenKt.class, zzen.zza);
        encoderConfig.registerEncoder(ViewUtilsApi19.class, zzcz.zza);
        encoderConfig.registerEncoder(ProvidersScreenKt.class, zzef.zza);
        encoderConfig.registerEncoder(ProfileCardKt.class, zzel.zza);
        encoderConfig.registerEncoder(LogcatScreenKt.class, zzdz.zza);
        encoderConfig.registerEncoder(ApkBrokenScreenKt.class, zzdv.zza);
        encoderConfig.registerEncoder(AppCrashedScreenKt.class, zzdw.zza);
        encoderConfig.registerEncoder(ParcelableKt.class, zzdu.zza);
        encoderConfig.registerEncoder(FilesScreenKt.class, zzdx.zza);
        encoderConfig.registerEncoder(zzje.class, zzeu.zza);
        encoderConfig.registerEncoder(zzjd.class, zzet.zza);
        encoderConfig.registerEncoder(zzap.class, zzbt.zza);
        encoderConfig.registerEncoder(zzld.class, zzgx.zza);
        encoderConfig.registerEncoder(zzlf.class, zzgz.zza);
        encoderConfig.registerEncoder(zzle.class, zzgy.zza);
        encoderConfig.registerEncoder(ViewGroupUtils.class, zzcx.zza);
        encoderConfig.registerEncoder(ContextKt.class, zzdn.zza);
        encoderConfig.registerEncoder(MainApplication.Companion.class, zzdm.zza);
        encoderConfig.registerEncoder(ApkDownloader.class, zzdl.zza);
        encoderConfig.registerEncoder(com.github.kr328.clash.core.util.NetKt.class, zzfa.zza);
        encoderConfig.registerEncoder(zzjk.class, zzfc.zza);
        encoderConfig.registerEncoder(TrafficKt.class, zzfb.zza);
        encoderConfig.registerEncoder(ViewModelKt.class, zzca.zza);
        encoderConfig.registerEncoder(LifecycleEffectKt.class, zzcb.zza);
        encoderConfig.registerEncoder(zzjn.class, zzff.zza);
        encoderConfig.registerEncoder(zzjq.class, zzfi.zza);
        encoderConfig.registerEncoder(zzjo.class, zzfg.zza);
        encoderConfig.registerEncoder(zzjp.class, zzfh.zza);
        encoderConfig.registerEncoder(NavDestination.Companion.class, zzce.zza);
        encoderConfig.registerEncoder(NavControllerViewModel.Companion.class, zzcf.zza);
        encoderConfig.registerEncoder(zzkx.class, zzgt.zza);
        encoderConfig.registerEncoder(zzkw.class, zzgs.zza);
        encoderConfig.registerEncoder(zzlb.class, zzgv.zza);
        encoderConfig.registerEncoder(zzlc.class, zzgw.zza);
        encoderConfig.registerEncoder(BroadcastKt.class, zzfq.zza);
        encoderConfig.registerEncoder(DeviceInfoKt.class, zzft.zza);
        encoderConfig.registerEncoder(CoroutineKt.class, zzfr.zza);
        encoderConfig.registerEncoder(DatabaseKt.class, zzfs.zza);
        encoderConfig.registerEncoder(NavGraphBuilderKt.class, zzck.zza);
        encoderConfig.registerEncoder(NavBackStackEntryProviderKt.class, zzcl.zza);
        encoderConfig.registerEncoder(UpdateDialogKt.class, zzeg.zza);
        encoderConfig.registerEncoder(MainAppKt.class, zzed.zza);
        encoderConfig.registerEncoder(LogFile.Companion.class, zzfj.zza);
        encoderConfig.registerEncoder(ProfileProcessorKt.class, zzfl.zza);
        encoderConfig.registerEncoder(I18nKt.class, zzfk.zza);
        encoderConfig.registerEncoder(NavOptionsBuilderKt.class, zzcg.zza);
        encoderConfig.registerEncoder(NavGraph.Companion.class, zzch.zza);
    }
}
