package androidx.compose.material3;

import androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda1;
import androidx.compose.ui.graphics.Color;

/* JADX INFO: compiled from: r8-map-id-0d0aa97d1fad3edd99b81b175d33e009605b3d4793e5c1d21bed0e5a39522f8f */
/* JADX INFO: loaded from: classes.dex */
public final class ColorScheme {
    public final long background;
    public ButtonColors defaultButtonColorsCached;
    public CheckboxColors defaultCheckboxColorsCached;
    public IconButtonColors defaultIconButtonColorsCached;
    public TextFieldColors defaultOutlinedTextFieldColorsCached;
    public RadioButtonColors defaultRadioButtonColorsCached;
    public ButtonColors defaultTextButtonColorsCached;
    public TopAppBarColors defaultTopAppBarColorsCached;
    public final long error;
    public final long errorContainer;
    public final long inverseOnSurface;
    public final long inversePrimary;
    public final long inverseSurface;
    public final long onBackground;
    public final long onError;
    public final long onErrorContainer;
    public final long onPrimary;
    public final long onPrimaryContainer;
    public final long onPrimaryFixed;
    public final long onPrimaryFixedVariant;
    public final long onSecondary;
    public final long onSecondaryContainer;
    public final long onSecondaryFixed;
    public final long onSecondaryFixedVariant;
    public final long onSurface;
    public final long onSurfaceVariant;
    public final long onTertiary;
    public final long onTertiaryContainer;
    public final long onTertiaryFixed;
    public final long onTertiaryFixedVariant;
    public final long outline;
    public final long outlineVariant;
    public final long primary;
    public final long primaryContainer;
    public final long primaryFixed;
    public final long primaryFixedDim;
    public final long scrim;
    public final long secondary;
    public final long secondaryContainer;
    public final long secondaryFixed;
    public final long secondaryFixedDim;
    public final long surface;
    public final long surfaceBright;
    public final long surfaceContainer;
    public final long surfaceContainerHigh;
    public final long surfaceContainerHighest;
    public final long surfaceContainerLow;
    public final long surfaceContainerLowest;
    public final long surfaceDim;
    public final long surfaceTint;
    public final long surfaceVariant;
    public final long tertiary;
    public final long tertiaryContainer;
    public final long tertiaryFixed;
    public final long tertiaryFixedDim;

    public ColorScheme(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.primary = j;
        this.onPrimary = j2;
        this.primaryContainer = j3;
        this.onPrimaryContainer = j4;
        this.inversePrimary = j5;
        this.secondary = j6;
        this.onSecondary = j7;
        this.secondaryContainer = j8;
        this.onSecondaryContainer = j9;
        this.tertiary = j10;
        this.onTertiary = j11;
        this.tertiaryContainer = j12;
        this.onTertiaryContainer = j13;
        this.background = j14;
        this.onBackground = j15;
        this.surface = j16;
        this.onSurface = j17;
        this.surfaceVariant = j18;
        this.onSurfaceVariant = j19;
        this.surfaceTint = j20;
        this.inverseSurface = j21;
        this.inverseOnSurface = j22;
        this.error = j23;
        this.onError = j24;
        this.errorContainer = j25;
        this.onErrorContainer = j26;
        this.outline = j27;
        this.outlineVariant = j28;
        this.scrim = j29;
        this.surfaceBright = j30;
        this.surfaceDim = j31;
        this.surfaceContainer = j32;
        this.surfaceContainerHigh = j33;
        this.surfaceContainerHighest = j34;
        this.surfaceContainerLow = j35;
        this.surfaceContainerLowest = j36;
        this.primaryFixed = j37;
        this.primaryFixedDim = j38;
        this.onPrimaryFixed = j39;
        this.onPrimaryFixedVariant = j40;
        this.secondaryFixed = j41;
        this.secondaryFixedDim = j42;
        this.onSecondaryFixed = j43;
        this.onSecondaryFixedVariant = j44;
        this.tertiaryFixed = j45;
        this.tertiaryFixedDim = j46;
        this.onTertiaryFixed = j47;
        this.onTertiaryFixedVariant = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.primary, sb, "onPrimary=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onPrimary, sb, "primaryContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.primaryContainer, sb, "onPrimaryContainer=");
        long j = this.onPrimaryContainer;
        ImageAnalysis$$ExternalSyntheticLambda1.m(j, sb, "inversePrimary=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.inversePrimary, sb, "secondary=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.secondary, sb, "onSecondary=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onSecondary, sb, "secondaryContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.secondaryContainer, sb, "onSecondaryContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onSecondaryContainer, sb, "tertiary=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.tertiary, sb, "onTertiary=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onTertiary, sb, "tertiaryContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.tertiaryContainer, sb, "onTertiaryContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onTertiaryContainer, sb, "background=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.background, sb, "onBackground=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onBackground, sb, "surface=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surface, sb, "onSurface=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onSurface, sb, "surfaceVariant=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceVariant, sb, "onSurfaceVariant=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onSurfaceVariant, sb, "surfaceTint=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceTint, sb, "inverseSurface=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.inverseSurface, sb, "inverseOnSurface=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.inverseOnSurface, sb, "error=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.error, sb, "onError=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onError, sb, "errorContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.errorContainer, sb, "onErrorContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onErrorContainer, sb, "outline=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.outline, sb, "outlineVariant=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.outlineVariant, sb, "scrim=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.scrim, sb, "surfaceBright=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceBright, sb, "surfaceDim=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceDim, sb, "surfaceContainer=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceContainer, sb, "surfaceContainerHigh=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceContainerHigh, sb, "surfaceContainerHighest=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceContainerHighest, sb, "surfaceContainerLow=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceContainerLow, sb, "surfaceContainerLowest=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.surfaceContainerLowest, sb, "primaryFixed=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.primaryFixed, sb, "primaryFixedDim=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.primaryFixedDim, sb, "onPrimaryFixed=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(j, sb, "onPrimaryFixedVariant=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onPrimaryFixedVariant, sb, "secondaryFixed=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.secondaryFixed, sb, "secondaryFixedDim=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.secondaryFixedDim, sb, "onSecondaryFixed=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onSecondaryFixed, sb, "onSecondaryFixedVariant=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onSecondaryFixedVariant, sb, "tertiaryFixed=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.tertiaryFixed, sb, "tertiaryFixedDim=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.tertiaryFixedDim, sb, "onTertiaryFixed=");
        ImageAnalysis$$ExternalSyntheticLambda1.m(this.onTertiaryFixed, sb, "onTertiaryFixedVariant=");
        sb.append((Object) Color.m441toStringimpl(this.onTertiaryFixedVariant));
        sb.append(')');
        return sb.toString();
    }
}
