package com.google.android.material;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class R$styleable {
    public static final int[] BaseProgressIndicator = {R.attr.indeterminate, com.koala.clash.R.attr.hideAnimationBehavior, com.koala.clash.R.attr.indicatorColor, com.koala.clash.R.attr.minHideDelay, com.koala.clash.R.attr.showAnimationBehavior, com.koala.clash.R.attr.showDelay, com.koala.clash.R.attr.trackColor, com.koala.clash.R.attr.trackCornerRadius, com.koala.clash.R.attr.trackThickness};
    public static final int[] BottomSheetBehavior_Layout = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.koala.clash.R.attr.backgroundTint, com.koala.clash.R.attr.behavior_draggable, com.koala.clash.R.attr.behavior_expandedOffset, com.koala.clash.R.attr.behavior_fitToContents, com.koala.clash.R.attr.behavior_halfExpandedRatio, com.koala.clash.R.attr.behavior_hideable, com.koala.clash.R.attr.behavior_peekHeight, com.koala.clash.R.attr.behavior_saveFlags, com.koala.clash.R.attr.behavior_skipCollapsed, com.koala.clash.R.attr.gestureInsetBottomIgnored, com.koala.clash.R.attr.marginLeftSystemWindowInsets, com.koala.clash.R.attr.marginRightSystemWindowInsets, com.koala.clash.R.attr.marginTopSystemWindowInsets, com.koala.clash.R.attr.paddingBottomSystemWindowInsets, com.koala.clash.R.attr.paddingLeftSystemWindowInsets, com.koala.clash.R.attr.paddingRightSystemWindowInsets, com.koala.clash.R.attr.paddingTopSystemWindowInsets, com.koala.clash.R.attr.shapeAppearance, com.koala.clash.R.attr.shapeAppearanceOverlay};
    public static final int[] Chip = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, com.koala.clash.R.attr.checkedIcon, com.koala.clash.R.attr.checkedIconEnabled, com.koala.clash.R.attr.checkedIconTint, com.koala.clash.R.attr.checkedIconVisible, com.koala.clash.R.attr.chipBackgroundColor, com.koala.clash.R.attr.chipCornerRadius, com.koala.clash.R.attr.chipEndPadding, com.koala.clash.R.attr.chipIcon, com.koala.clash.R.attr.chipIconEnabled, com.koala.clash.R.attr.chipIconSize, com.koala.clash.R.attr.chipIconTint, com.koala.clash.R.attr.chipIconVisible, com.koala.clash.R.attr.chipMinHeight, com.koala.clash.R.attr.chipMinTouchTargetSize, com.koala.clash.R.attr.chipStartPadding, com.koala.clash.R.attr.chipStrokeColor, com.koala.clash.R.attr.chipStrokeWidth, com.koala.clash.R.attr.chipSurfaceColor, com.koala.clash.R.attr.closeIcon, com.koala.clash.R.attr.closeIconEnabled, com.koala.clash.R.attr.closeIconEndPadding, com.koala.clash.R.attr.closeIconSize, com.koala.clash.R.attr.closeIconStartPadding, com.koala.clash.R.attr.closeIconTint, com.koala.clash.R.attr.closeIconVisible, com.koala.clash.R.attr.ensureMinTouchTargetSize, com.koala.clash.R.attr.hideMotionSpec, com.koala.clash.R.attr.iconEndPadding, com.koala.clash.R.attr.iconStartPadding, com.koala.clash.R.attr.rippleColor, com.koala.clash.R.attr.shapeAppearance, com.koala.clash.R.attr.shapeAppearanceOverlay, com.koala.clash.R.attr.showMotionSpec, com.koala.clash.R.attr.textEndPadding, com.koala.clash.R.attr.textStartPadding};
    public static final int[] ChipGroup = {com.koala.clash.R.attr.checkedChip, com.koala.clash.R.attr.chipSpacing, com.koala.clash.R.attr.chipSpacingHorizontal, com.koala.clash.R.attr.chipSpacingVertical, com.koala.clash.R.attr.selectionRequired, com.koala.clash.R.attr.singleLine, com.koala.clash.R.attr.singleSelection};
    public static final int[] ClockFaceView = {com.koala.clash.R.attr.clockFaceBackgroundColor, com.koala.clash.R.attr.clockNumberTextColor};
    public static final int[] ClockHandView = {com.koala.clash.R.attr.clockHandColor, com.koala.clash.R.attr.materialCircleRadius, com.koala.clash.R.attr.selectorSize};
    public static final int[] ExtendedFloatingActionButton_Behavior_Layout = {com.koala.clash.R.attr.behavior_autoHide, com.koala.clash.R.attr.behavior_autoShrink};
    public static final int[] FloatingActionButton_Behavior_Layout = {com.koala.clash.R.attr.behavior_autoHide};
    public static final int[] FlowLayout = {com.koala.clash.R.attr.itemSpacing, com.koala.clash.R.attr.lineSpacing};
    public static final int[] ForegroundLinearLayout = {R.attr.foreground, R.attr.foregroundGravity, com.koala.clash.R.attr.foregroundInsidePadding};
    public static final int[] LinearProgressIndicator = {com.koala.clash.R.attr.indeterminateAnimationType, com.koala.clash.R.attr.indicatorDirectionLinear};
    public static final int[] MaterialAutoCompleteTextView = {R.attr.inputType, com.koala.clash.R.attr.simpleItemLayout, com.koala.clash.R.attr.simpleItems};
    public static final int[] MaterialButton = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.koala.clash.R.attr.backgroundTint, com.koala.clash.R.attr.backgroundTintMode, com.koala.clash.R.attr.cornerRadius, com.koala.clash.R.attr.elevation, com.koala.clash.R.attr.icon, com.koala.clash.R.attr.iconGravity, com.koala.clash.R.attr.iconPadding, com.koala.clash.R.attr.iconSize, com.koala.clash.R.attr.iconTint, com.koala.clash.R.attr.iconTintMode, com.koala.clash.R.attr.rippleColor, com.koala.clash.R.attr.shapeAppearance, com.koala.clash.R.attr.shapeAppearanceOverlay, com.koala.clash.R.attr.strokeColor, com.koala.clash.R.attr.strokeWidth};
    public static final int[] MaterialButtonToggleGroup = {com.koala.clash.R.attr.checkedButton, com.koala.clash.R.attr.selectionRequired, com.koala.clash.R.attr.singleSelection};
    public static final int[] MaterialCalendar = {R.attr.windowFullscreen, com.koala.clash.R.attr.dayInvalidStyle, com.koala.clash.R.attr.daySelectedStyle, com.koala.clash.R.attr.dayStyle, com.koala.clash.R.attr.dayTodayStyle, com.koala.clash.R.attr.nestedScrollable, com.koala.clash.R.attr.rangeFillColor, com.koala.clash.R.attr.yearSelectedStyle, com.koala.clash.R.attr.yearStyle, com.koala.clash.R.attr.yearTodayStyle};
    public static final int[] MaterialCalendarItem = {R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, com.koala.clash.R.attr.itemFillColor, com.koala.clash.R.attr.itemShapeAppearance, com.koala.clash.R.attr.itemShapeAppearanceOverlay, com.koala.clash.R.attr.itemStrokeColor, com.koala.clash.R.attr.itemStrokeWidth, com.koala.clash.R.attr.itemTextColor};
    public static final int[] MaterialCheckBox = {com.koala.clash.R.attr.buttonTint, com.koala.clash.R.attr.centerIfNoTextEnabled, com.koala.clash.R.attr.useMaterialThemeColors};
    public static final int[] MaterialRadioButton = {com.koala.clash.R.attr.buttonTint, com.koala.clash.R.attr.useMaterialThemeColors};
    public static final int[] MaterialShape = {com.koala.clash.R.attr.shapeAppearance, com.koala.clash.R.attr.shapeAppearanceOverlay};
    public static final int[] MaterialTextAppearance = {R.attr.letterSpacing, R.attr.lineHeight, com.koala.clash.R.attr.lineHeight};
    public static final int[] MaterialTextView = {R.attr.textAppearance, R.attr.lineHeight, com.koala.clash.R.attr.lineHeight};
    public static final int[] MaterialToolbar = {com.koala.clash.R.attr.logoAdjustViewBounds, com.koala.clash.R.attr.logoScaleType, com.koala.clash.R.attr.navigationIconTint, com.koala.clash.R.attr.subtitleCentered, com.koala.clash.R.attr.titleCentered};
    public static final int[] RadialViewGroup = {com.koala.clash.R.attr.materialCircleRadius};
    public static final int[] ScrollingViewBehavior_Layout = {com.koala.clash.R.attr.behavior_overlapTop};
    public static final int[] ShapeAppearance = {com.koala.clash.R.attr.cornerFamily, com.koala.clash.R.attr.cornerFamilyBottomLeft, com.koala.clash.R.attr.cornerFamilyBottomRight, com.koala.clash.R.attr.cornerFamilyTopLeft, com.koala.clash.R.attr.cornerFamilyTopRight, com.koala.clash.R.attr.cornerSize, com.koala.clash.R.attr.cornerSizeBottomLeft, com.koala.clash.R.attr.cornerSizeBottomRight, com.koala.clash.R.attr.cornerSizeTopLeft, com.koala.clash.R.attr.cornerSizeTopRight};
    public static final int[] SnackbarLayout = {R.attr.maxWidth, com.koala.clash.R.attr.actionTextColorAlpha, com.koala.clash.R.attr.animationMode, com.koala.clash.R.attr.backgroundOverlayColorAlpha, com.koala.clash.R.attr.backgroundTint, com.koala.clash.R.attr.backgroundTintMode, com.koala.clash.R.attr.elevation, com.koala.clash.R.attr.maxActionInlineWidth};
    public static final int[] SwitchMaterial = {com.koala.clash.R.attr.useMaterialThemeColors};
    public static final int[] TextAppearance = {R.attr.textSize, R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.textColorHint, R.attr.textColorLink, R.attr.shadowColor, R.attr.shadowDx, R.attr.shadowDy, R.attr.shadowRadius, R.attr.fontFamily, R.attr.textFontWeight, com.koala.clash.R.attr.fontFamily, com.koala.clash.R.attr.fontVariationSettings, com.koala.clash.R.attr.textAllCaps, com.koala.clash.R.attr.textLocale};
    public static final int[] TextInputEditText = {com.koala.clash.R.attr.textInputLayoutFocusedRectEnabled};
    public static final int[] TextInputLayout = {R.attr.enabled, R.attr.textColorHint, R.attr.maxWidth, R.attr.minWidth, R.attr.hint, R.attr.maxEms, R.attr.minEms, com.koala.clash.R.attr.boxBackgroundColor, com.koala.clash.R.attr.boxBackgroundMode, com.koala.clash.R.attr.boxCollapsedPaddingTop, com.koala.clash.R.attr.boxCornerRadiusBottomEnd, com.koala.clash.R.attr.boxCornerRadiusBottomStart, com.koala.clash.R.attr.boxCornerRadiusTopEnd, com.koala.clash.R.attr.boxCornerRadiusTopStart, com.koala.clash.R.attr.boxStrokeColor, com.koala.clash.R.attr.boxStrokeErrorColor, com.koala.clash.R.attr.boxStrokeWidth, com.koala.clash.R.attr.boxStrokeWidthFocused, com.koala.clash.R.attr.counterEnabled, com.koala.clash.R.attr.counterMaxLength, com.koala.clash.R.attr.counterOverflowTextAppearance, com.koala.clash.R.attr.counterOverflowTextColor, com.koala.clash.R.attr.counterTextAppearance, com.koala.clash.R.attr.counterTextColor, com.koala.clash.R.attr.endIconCheckable, com.koala.clash.R.attr.endIconContentDescription, com.koala.clash.R.attr.endIconDrawable, com.koala.clash.R.attr.endIconMode, com.koala.clash.R.attr.endIconTint, com.koala.clash.R.attr.endIconTintMode, com.koala.clash.R.attr.errorContentDescription, com.koala.clash.R.attr.errorEnabled, com.koala.clash.R.attr.errorIconDrawable, com.koala.clash.R.attr.errorIconTint, com.koala.clash.R.attr.errorIconTintMode, com.koala.clash.R.attr.errorTextAppearance, com.koala.clash.R.attr.errorTextColor, com.koala.clash.R.attr.expandedHintEnabled, com.koala.clash.R.attr.helperText, com.koala.clash.R.attr.helperTextEnabled, com.koala.clash.R.attr.helperTextTextAppearance, com.koala.clash.R.attr.helperTextTextColor, com.koala.clash.R.attr.hintAnimationEnabled, com.koala.clash.R.attr.hintEnabled, com.koala.clash.R.attr.hintTextAppearance, com.koala.clash.R.attr.hintTextColor, com.koala.clash.R.attr.passwordToggleContentDescription, com.koala.clash.R.attr.passwordToggleDrawable, com.koala.clash.R.attr.passwordToggleEnabled, com.koala.clash.R.attr.passwordToggleTint, com.koala.clash.R.attr.passwordToggleTintMode, com.koala.clash.R.attr.placeholderText, com.koala.clash.R.attr.placeholderTextAppearance, com.koala.clash.R.attr.placeholderTextColor, com.koala.clash.R.attr.prefixText, com.koala.clash.R.attr.prefixTextAppearance, com.koala.clash.R.attr.prefixTextColor, com.koala.clash.R.attr.shapeAppearance, com.koala.clash.R.attr.shapeAppearanceOverlay, com.koala.clash.R.attr.startIconCheckable, com.koala.clash.R.attr.startIconContentDescription, com.koala.clash.R.attr.startIconDrawable, com.koala.clash.R.attr.startIconTint, com.koala.clash.R.attr.startIconTintMode, com.koala.clash.R.attr.suffixText, com.koala.clash.R.attr.suffixTextAppearance, com.koala.clash.R.attr.suffixTextColor};
    public static final int[] ThemeEnforcement = {R.attr.textAppearance, com.koala.clash.R.attr.enforceMaterialTheme, com.koala.clash.R.attr.enforceTextAppearance};
}
